In [9]:
import re

class ReaderSWF:
    def __init__(self, filename):
        self.filename = filename
        self.number_of_jobs = None
        self.number_of_processors = None
        self.jobs_info = {'p': [], '~p': [], 'q': [], 'r': []}
        self.read_and_extract_data()

    def read_and_extract_data(self):
        with open(self.filename, 'r') as reader:
            jobs_counter = 0
            for line in reader.readlines():
                
                row = re.split(" +", line.lstrip(" "))
                row[-1] = row[-1].rstrip()


                if row[0].startswith(";"):
                    if "MaxProcs:" in row:
                        self.number_of_processors = int(row[row.index("MaxProcs:") + 1])
                    elif "MaxNodes:" in row:
                        self.number_of_processors = int(row[row.index("MaxNodes:") + 1])
                    continue

                # row[4] is q, row[3] is p, row[8] is ~p, and row[1] is r
                if float(row[4]) > 0 and float(row[4]) <= self.number_of_processors and float(row[3]) > 0 and float(row[8]) > 0:
                    jobs_counter += 1
                    self.jobs_info['p'].append(float(row[3]))
                    self.jobs_info['~p'].append(float(row[8]))
                    self.jobs_info['q'].append(float(row[4]))
                    self.jobs_info['r'].append(float(row[1]))
            
            self.number_of_jobs = jobs_counter
    def write_data(self, filename):
        with open(self.filename, 'r') as reader:
            with open(filename, 'w') as writer:
                jobs_counter = 0
                for line in reader.readlines():
                    
                    row = re.split(" +", line.lstrip(" "))
                    row[-1] = row[-1].rstrip()
                    if not(row[0].startswith(";")) and float(row[4]) > 0 and float(row[4]) <= self.number_of_processors and float(row[3]) > 0 and float(row[8]) > 0:
                        
                        row[3]=str(self.jobs_info['p'][jobs_counter])
                        row[8]=str(self.jobs_info['~p'][jobs_counter])
                        row[4]=str(self.jobs_info['q'][jobs_counter])
                        row[1]=str(self.jobs_info['r'][jobs_counter])
                        jobs_counter += 1
                    new_row=[]
                    for x in row :
                        new_row.append(x)
                        new_row.append(" ")
                    new_row[len(new_row)-1]='\n'
                    writer.writelines(new_row)

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler

df1=ReaderSWF("../../data/workloads/lublin_256.swf")
df2=ReaderSWF("../../data/workloads/lublin_256.swf")
df=pd.DataFrame.from_dict(df1.jobs_info)
scaler1=StandardScaler()
scaler2=MinMaxScaler()
arr2=scaler1.fit_transform(df)
arr3=scaler2.fit_transform(df)

df_norm_std=pd.DataFrame(arr2, columns = ["p","~p","q","r"])
df_norm_minmax=pd.DataFrame(arr3, columns = ["p","~p","q","r"])
dict_minmax=df_norm_minmax.to_dict('list')
dict_std=df_norm_std.to_dict('list')
df1.jobs_info=dict_std
df2.jobs_info=dict_minmax
df1.write_data("../../data/workloads/lublin_256_norm_std.swf")
df2.write_data("../../data/workloads/lublin_256_norm_minmax.swf")
df3=ReaderSWF("../../data/workloads/lublin_256_norm_std.swf")
dict=pd.DataFrame.from_dict(df3.jobs_info)
dict

NameError: name 'ReaderSWF' is not defined

In [12]:
df1=ReaderSWF("../../data/workloads/SDSC-BLUE-2000-4.2-cln.swf")
df2=ReaderSWF("../../data/workloads/SDSC-BLUE-2000-4.2-cln.swf")
df=pd.DataFrame.from_dict(df1.jobs_info)
scaler1=StandardScaler()
scaler2=MinMaxScaler()
arr2=scaler1.fit_transform(df)
arr3=scaler2.fit_transform(df)

df_norm_std=pd.DataFrame(arr2, columns = ["p","~p","q","r"])
df_norm_minmax=pd.DataFrame(arr3, columns = ["p","~p","q","r"])
dict_minmax=df_norm_minmax.to_dict('list')
dict_std=df_norm_std.to_dict('list')
df1.jobs_info=dict_std
df2.jobs_info=dict_minmax
df1.write_data("../../data/workloads/SDSC-BLUE-2000-4.2-cln_norm_std.swf")
df2.write_data("../../data/workloads/SDSC-BLUE-2000-4.2-cln_norm_minmax.swf")
df3=ReaderSWF("../../data/workloads/SDSC-BLUE-2000-4.2-cln_norm_minmax.swf")
dict=pd.DataFrame.from_dict(df3.jobs_info)
dict

               p        ~p         q         r
0       0.082467  0.107140  0.216783  0.000000
1       0.017460  0.047616  0.216783  0.000002
2       0.020590  0.106644  0.216783  0.000038
3       0.004528  0.099203  0.048951  0.000087
4       0.000068  0.107140  0.020979  0.000113
...          ...       ...       ...       ...
110632  0.002391  0.214283  0.020979  0.999946
110633  0.017106  0.023806  0.076923  0.999958
110634  0.003573  0.214283  0.020979  0.999964
110635  0.029258  0.029759  0.020979  0.999966
110636  0.210374  0.214283  0.020979  0.999998

[110637 rows x 4 columns]

In [13]:
df1=ReaderSWF("../../data/workloads/CTC-SP2-1996-3.1-cln.swf")
df2=ReaderSWF("../../data/workloads/CTC-SP2-1996-3.1-cln.swf")
df=pd.DataFrame.from_dict(df1.jobs_info)
scaler1=StandardScaler()
scaler2=MinMaxScaler()
arr2=scaler1.fit_transform(df)
arr3=scaler2.fit_transform(df)

df_norm_std=pd.DataFrame(arr2, columns = ["p","~p","q","r"])
df_norm_minmax=pd.DataFrame(arr3, columns = ["p","~p","q","r"])
dict_minmax=df_norm_minmax.to_dict('list')
dict_std=df_norm_std.to_dict('list')
df1.jobs_info=dict_std
df2.jobs_info=dict_minmax
df1.write_data("../../data/workloads/CTC-SP2-1996-3.1-cln_norm_std.swf")
df2.write_data("../../data/workloads/CTC-SP2-1996-3.1-cln_norm_minmax.swf")
df3=ReaderSWF("../../data/workloads/CTC-SP2-1996-3.1-cln_norm_minmax.swf")
dict=pd.DataFrame.from_dict(df3.jobs_info)
dict

              p        ~p         q         r
0      0.013001  0.539535  0.910448  0.000000
1      0.489840  0.539535  0.910448  0.006729
2      0.409628  1.000000  0.188060  0.010596
3      0.403656  1.000000  0.188060  0.010599
4      0.468158  1.000000  0.188060  0.010604
...         ...       ...       ...       ...
39387  0.051835  1.000000  0.008955  0.999550
39388  0.150631  0.162791  0.044776  0.999572
39389  0.250955  0.274419  0.005970  0.999646
39390  0.012987  0.009302  0.035821  0.999750
39391  0.036224  0.162791  0.008955  1.000000

[39392 rows x 4 columns]

In [8]:
import pandas as pd
import numpy as np
import math
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("../../data/global_training_data_GA.csv")
df.columns=["p","q","r","y"]
y_save=df["y"]

df=df[["p","q","r"]]
# Calcul de la moyenne du nombre de tÃ¢ches (arrondie Ã  l'entier supÃ©rieur)
num_tasks = [2835, 3836, 4089, 2987, 3079, 3446, 3152, 3554, 4560, 3824,
             2950, 4127, 3257, 2718, 3157, 4559, 3551, 3559, 3062, 2726,
             3376, 2773]
mean_tasks = math.ceil(np.mean(num_tasks))

# Fonction pour diviser un DataFrame en morceaux de taille Ã©gale
def split_dataframe(df, chunk_size):
    chunks = [df[i:i + chunk_size] for i in range(0, len(df), chunk_size)]
    return chunks

# Diviser le DataFrame en morceaux de taille Ã©gale Ã  la moyenne du nombre de tÃ¢ches
chunks = split_dataframe(df, mean_tasks)

# Appliquer la normalisation standard sur chaque DataFrame
scaler = StandardScaler()
normalized_chunks = [pd.DataFrame(scaler.fit_transform(chunk), columns=chunk.columns) for chunk in chunks]

# ConcatÃ©ner de nouveau les morceaux normalisÃ©s
normalized_df = pd.concat(normalized_chunks, ignore_index=True)
normalized_df=pd.concat([normalized_df,y_save],axis=1)
# Affichage du DataFrame normalisÃ©
normalized_df.to_csv("../../data/global_training_data_GA_norm_std.csv",index=False)
normalized_df

              p         q          r        y
0     -0.547240 -0.468501  -0.305366  0.34375
1     -0.550135  0.206751  -0.303868  0.12500
2     -0.531317 -0.153384  -0.274187  0.43750
3     -0.545236 -0.491010  -0.272014  0.28125
4      0.469927  2.367558  -0.271721  0.78125
...         ...       ...        ...      ...
81339  0.997469  0.277422   2.034861  0.87500
81340 -0.432675  1.062837   2.039286  0.75000
81341 -0.543559 -0.483450  12.271025  0.93750
81342 -0.536511 -0.458905  12.273105  0.96875
81343 -0.540255 -0.041653  12.280761  1.00000

[81344 rows x 4 columns]

In [9]:
df1=pd.read_csv("../../data/global_training_data_GA.csv")
df1.columns=["p","q","r","y"]
y_save=df1["y"]

df1=df1[["p","q","r"]]

scaler1=StandardScaler()
scaler2=MinMaxScaler()
arr2=scaler1.fit_transform(df1)
arr3=scaler2.fit_transform(df1)
df2=pd.DataFrame(arr2)
df3=pd.DataFrame(arr3)
df2=pd.concat([df2,y_save],axis=1)
df3=pd.concat([df3,y_save],axis=1)
print(df2)

df2.to_csv("../../data/global_training_data_GA_norm_std.csv",index=False)
df3.to_csv("../../data/global_training_data_GA_norm_minmax.csv",index=False)

              0         1         2        y
0     -0.554045 -0.465939 -0.322933  0.34375
1     -0.556989  0.232001 -0.321333  0.12500
2     -0.537855 -0.140234 -0.289614  0.43750
3     -0.552007 -0.489203 -0.287292  0.28125
4      0.480176  2.465407 -0.286978  0.78125
...         ...       ...       ...      ...
81339  1.027005  0.232001  1.359182  0.87500
81340 -0.443434  0.976469  1.362319  0.75000
81341 -0.557442 -0.489203  8.615771  0.93750
81342 -0.550196 -0.465939  8.617246  0.96875
81343 -0.554045 -0.070440  8.622673  1.00000

[81344 rows x 4 columns]

In [24]:
df1=pd.read_csv("../../data/global_training_data_GA_MEM.csv")
scaler1=StandardScaler()
scaler2=MinMaxScaler()
arr2=scaler1.fit_transform(df1)
arr3=scaler2.fit_transform(df1)
df2=pd.DataFrame(arr2)
df3=pd.DataFrame(arr3)
df2.to_csv("../../data/global_training_data_GA_MEM_norm_std.csv",index=False)
df3.to_csv("../../data/global_training_data_GA_MEM_norm_minmax.csv",index=False)